### PR TITLE
rebrand the whole thing why not

### PR DESCRIPTION
**Pull request by mattpannella**
woof

### CODE REVIEW

**Comment by irbrad** [comment]
But why?

**Comment by mattpannella** [comment]
> But why?

because I'm tired of having to explain the difference between this app and retrodriven's since they basically have the same name. also since I never really "named" this thing and I think it will be easier than everyone having to call it "the pannella updater" or whatever lol
Screenshot_20240118-212415

**Comment by irbrad** [comment]
Hah, that makes sense!  Rather than pupdate might I suggest something a bit more memorable?  Like how everyone knows what Dophin is for?  If someone gets a pocket, you need to grab: `this name`?

Renaming is something you can only do once every so often.  This tool is great and I wouldn't want it to fall by the wayside because people forget about it.  My two cents at least.

**Comment by mattpannella** [comment]
well regardless of what I call it I'm not super worried about it getting lost. when I rename this repo all the old links will still work just fine and redirect. github handles it all for you

**Pull request merged**
