### PR TITLE
updated version to 3.0.0

### PR DESCRIPTION
**Pull request by mattpannella**

### CODE REVIEW

**Comment by michaelsmoody** [comment]
@mattpannella 

🚨FAIRLY LARGE EMERGENCY SITUATION🚨

I don't know if malware was introduced into your supply chain, but Windows Defender, and Virustotal are reporting malware in (AT LEAST) the pupdate_win release!

**Bkav Pro - W64.AIDetectMalware**
**SecureAge - Malicious**
**Cynet - Malicious (score: 100)**
**Windows Defender - Trojan:Script/Wacatac.B!ml**

This prevented both download AND update. I needed to manually allow it to even scan it!

**Comment by mattpannella** [comment]
> @mattpannella
> 
> 🚨FAIRLY LARGE EMERGENCY SITUATION🚨
> 
> I don't know if malware was introduced into your supply chain, but Windows Defender, and Virustotal are reporting malware in (AT LEAST) the pupdate_win release!
> 
> **Bkav Pro - W64.AIDetectMalware** **SecureAge - Malicious** **Cynet - Malicious (score: 100)** **Windows Defender - Trojan:Script/Wacatac.B!ml**
> 
> This prevented both download AND update. I needed to manually allow it to even scan it!

thats annoying
i mean, it's a false positive. you can check the github workflow where i build the app. nothing has changed

**Comment by michaelsmoody** [comment]
> > @mattpannella
> > 🚨FAIRLY LARGE EMERGENCY SITUATION🚨
> > I don't know if malware was introduced into your supply chain, but Windows Defender, and Virustotal are reporting malware in (AT LEAST) the pupdate_win release!
> > **Bkav Pro - W64.AIDetectMalware** **SecureAge - Malicious** **Cynet - Malicious (score: 100)** **Windows Defender - Trojan:Script/Wacatac.B!ml**
> > This prevented both download AND update. I needed to manually allow it to even scan it!
> 
> thats annoying i mean, it's a false positive. you can check the github workflow where i build the app. nothing has changed

I believe you entirely. I'm going to try to track it back to a specific cause. Unfortunately, multiple scanners are detecting it and Windows Defender is preventing update. Edge Smart Screen is actively removing the download of the zip asset from GitHub.

It looks like this will bear investigation.

("What could go wrong?")

**Comment by mattpannella** [comment]
> > > @mattpannella
> > > 🚨FAIRLY LARGE EMERGENCY SITUATION🚨
> > > I don't know if malware was introduced into your supply chain, but Windows Defender, and Virustotal are reporting malware in (AT LEAST) the pupdate_win release!
> > > **Bkav Pro - W64.AIDetectMalware** **SecureAge - Malicious** **Cynet - Malicious (score: 100)** **Windows Defender - Trojan:Script/Wacatac.B!ml**
> > > This prevented both download AND update. I needed to manually allow it to even scan it!
> > 
> > 
> > thats annoying i mean, it's a false positive. you can check the github workflow where i build the app. nothing has changed
> 
> I believe you entirely. I'm going to try to track it back to a specific cause. Unfortunately, multiple scanners are detecting it and Windows Defender is preventing update. Edge Smart Screen is actively removing the download of the zip asset from GitHub.
> 
> It looks like this will bear investigation.
> 
> ("What could go wrong?")

huh, thats odd. unless people just havent told me, i havent had any false positives til right now
this latest release i literally only changed the name of the app and executable, and added like 3 or 4 lines of code haha.

**Comment by ericmorand** [comment]
From my experience, the previous version was already detected as a malware by Windows. Not a big deal though - this is quite common from the OS to trigger false positive.

**Comment by chriscamicas** [comment]
I'm having the same issue on macos (arm64) with [Crowdstrike EDR](https://www.crowdstrike.fr/falcon-platform/)

**Pull request merged**
